config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get 'login'
      post 'new_login'
      get 'logout'
    end
  end

  resources :artists do
    resource :artist_genres
    resources :albums do
      resources :songs
    end
  end

  resources :record_labels, path: 'record_labels'

  resources :genres

  root to: 'welcome#index'
  get 'search/search'


  get '/about', :to => 'welcome#about'

  get 'welcome/about'


end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :artist_genres
  has_many :artists, through: :artist_genres

  validates :name, presence: true
  validates :name, uniqueness:{case_sensitive: false}

  before_validation :format_name

  def downcase_name
    self.name.downcase!
  end

  def strip_whitespace
    self.name.strip!
  end

  def format_name
    strip_whitespace
    downcase_name
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.create(genre_params)
    if genre.save
      redirect_to genre_path(genre)
    else
      @genre = genre
      render 'new'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find_or_create_by(genre_params)
    if genre.save
      redirect_to genre_path(genre)
    else
      redirect_to edit_genre_path
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to genres_path
  end

  def genre_params
    params.require(:genre).permit(
      :name,
      :description)
  end

end

app/views/genres/_form.html.erb
<div class="edit_title">
  <h1>Create New Genre</h1>
</div>

<%= render 'shared/error_messages', target: @genre %>
<div class="container">
  <%= form_for @genre, html: {class: "form-horizontal"} do |f| %>
    <div class = "form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class = "col-sm-3">
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
    </div>
    <div class = "form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class = "col-sm-5">
        <%= f.text_area :description, class: "form-control", rows: 5 %>
      </div>
    </div>
    <div class = "col-sm-offset-2 col-sm-8">
      <%= f.submit :class=>'button' %>
    </div>
  <% end %>
</div>

app/views/genres/edit.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>


<%= render 'form' %>
<%= link_to 'Delete Genre', genre_path(@genre), method: :delete %>

app/views/genres/index.html.erb
<style>

#logo {
	margin-bottom: 20px;
	vertical-align: middle;
}

.banner container-fluid {
	height: 50px;
}

.nav_links {
/*	margin-top: 50px;*/
margin-top: -50px;
}

.navbar-header {
	margin-top: 10px;
}

</style>

<section>
	<header>
		<nav class="navbar navbar-default navbar-static-top" role="navigation">
			<div class="banner container-fluid">
				<div class="navbar-header">
					<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<DIV CLASS="nav_links">
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="header_ul nav navbar-nav navbar-right">
						<% if session[:user_id] %>
							<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
							<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
						<% else %>
							<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
						<%end%>
						<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
						<li class="main_ul"><a href='/artists'>Artists</a></li>
						<li class="main_ul"><a href='/genres'>Genres</a></li>
						<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
					</ul>
				</div>
			</DIV>
			</div>
		</nav>
	</header>

	<div id="genre-index-title">
		<div class="title">
			<h1>Genres</h1>
		</div>
	</div>

	<div class="list">
		<ul>
			<% @genres.each do |genre| %>
			  <li><%= link_to genre.name, genre_path(genre), :class=>"artist" %></li>
			<% end %>
		</ul>

		<p><%= link_to 'add new genre', new_genre_path, class: 'new_artist_link'  %></p>
	</div>

	<section class="scroll-top-wrapper">
		<span class="scroll-top-inner">
			Top
		</span>
	</section>
</section>

app/views/genres/new.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>


<%= render 'form' %>

app/views/genres/show.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>


<p><%= @genre.name %></p>
<p><%= @genre.description %></p>
<%= link_to 'edit genre', edit_genre_path %>
<%= link_to 'back to all genres', genres_path %>