config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get 'login'
      post 'new_login'
      get 'logout'
    end
  end

  resources :artists do
    resource :artist_genres
    resources :albums do
      resources :songs
    end
  end

  resources :record_labels, path: 'record_labels'

  resources :genres

  root to: 'welcome#index'
  get 'search/search'


  get '/about', :to => 'welcome#about'

  get 'welcome/about'


end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :record_label
  has_many :albums
  has_many :artist_genres
  has_many :genres, through: :artist_genres
  has_many :songs

  has_attached_file :avatar, styles: {
    medium: "300x300>",
    thumb: "100x100>" },
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :stage_name, uniqueness: {case_sensitive: false}
  validates :stage_name, :description, presence: true


  def all_genres
    if self.genres.count < 1
      'add genres'
    else
      self.genres.map{|genre|genre.name}.join(', ')
    end
  end

  def update_genres(genres_array)
    genre_objects_array = genres_array.map do |genre_name|
      Genre.find_or_create_by(name: genre_name)
    end

    genre_objects_array.each do |genre|
      unless self.genres.include?(genre)
        self.genres << genre
      end
    end
  end

  def to_param
    "#{id}-#{stage_name.parameterize}"
  end

  def calculate_age
    unless date_of_birth == nil
      ave_seconds_in_a_year = 31536000
      age_as_float = (Time.now - date_of_birth) / ave_seconds_in_a_year
      age_as_float.floor
    end
  end

  def birthday
    unless date_of_birth == nil
      dob = date_of_birth.strftime("%A, %B %d, %Y")
    else
      'none listed'
    end
  end

  def display_birth_info
    "#{birthday} (Age:#{calculate_age || "N/A"})"
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def create
    artist = Artist.new(artist_params)
    if artist.save
      redirect_to artist_path(artist)
    else
      @artist = artist
      render 'new'
    end
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    artist = Artist.find(params[:id])
    if artist.update_attributes(artist_params)
      redirect_to artist_path(artist)
    else
      redirect_to edit_artist_path(artist)
    end
  end

  def destroy
    artist = Artist.find(params[:id])
    artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(
      :avatar,
      :stage_name,
      :birth_name,
      :date_of_birth,
      :description)
  end
end

app/views/artists/_albums_list.html.erb
<div class = "container">
  <h3 class="album-sec-title">Albums</h3>
  	
		<p><%= link_to 'add an album', new_artist_album_path(@artist), :class=>'new_artist_link' %></p>
  	<ul class="albums">
	    <% @artist.albums.each do |album| %>
		    	
	    	<li class="album col-sm-5 col-sm-offset-1" >
		    	<% if album.avatar.url == "/images/original/missing.png" %>
		      <%= image_tag "generic_album.png", id:"profile", alt: "artist avatar", style: "width:20em;height:20em" %>
			    <% else %>
			      <%= image_tag album.avatar.url(:medium) , id: "profile", alt: "artist_avatar", style: "width:20em;height:22em" %>
			    <%end %>
			      <p id="album-title"><%= link_to album.title, artist_album_path(@artist, album) %></p>
			    <% end %>
		    </li>
  		</ul>
  
</div>

app/views/artists/_form.html.erb
<section >    
    <div class = "container">
        <%= form_for @artist, html: { multipart: true, class: "form-horizontal" } do |f| %>
            <%= render 'shared/error_messages', target: @artist %>
            <div class="form-group">
                <%= f.label 'stage name', class: "col-sm-2 control-label"%>
                <div class="col-sm-3">
                    <%= f.text_field :stage_name, class: "edit-option form-control", required: true %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label 'birth name (if different)', class: "col-sm-2 control-label"%>
                <div class = "col-sm-3">
                    <%= f.text_field :birth_name, class: "edit-option form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label 'date of birth', class: "col-sm-2 control-label" %>
                <div class = "col-sm-10">
                    <%= f.date_select :date_of_birth, start_year: 1900, end_year: Time.now.year %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label 'description', class: "col-sm-2 control-label" %>
                <div class = "col-sm-6">
                    <%= f.text_area :description, class: "edit-option form-control", rows:5 , required: true %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label 'upload photo', class: "col-sm-2 control-label"%>
                <div class = "col-sm-3">
                    <%= f.file_field :avatar, class: "form-control"  %>
                </div>
            </div>
            <div class="form-group">
                <div class = "col-sm-offset-2 col-sm-8">
                    <%= f.submit :class=>'button' %>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/artists/edit.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>



<div class="edit_title">
	<h1>Edit Artist</h1>

</div>

<%= render 'form' %>
<%= render partial: 'albums/artist_albums', locals: { artist: @artist } %>
<%= link_to "Edit Artist's Genres", edit_artist_artist_genres_path(@artist) %>
<%= link_to "Delete Artist", artist_path(@artist), method: :delete %>

app/views/artists/index.html.erb
<section>
	<header>
		<nav class="navbar navbar-default navbar-static-top" role="navigation">
			<div class="banner container-fluid">
				<div class="navbar-header">
					<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="header_ul nav navbar-nav navbar-right">
						<% if session[:user_id] %>
							<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
							<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
						<% else %>
							<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
						<%end%>
						<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
						<li class="main_ul"><a href='/artists'>Artists</a></li>
						<li class="main_ul"><a href='/genres'>Genres</a></li>
						<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>



	<div id="artist-index-title">
		<div class="title">
			<h1>Artists</h1>
		</div>
	</div>


	<div class="list">
		<ul>
			<% @artists.each do |artist| %>
			  <li><%= link_to artist.stage_name, artist_path(artist), :class=>"artist" %></li>
			<% end %>
		</ul>

		<p><a class="new_artist_link" href="/artists/new">Add New Artist</a></p>
	</div>

	<section class="scroll-top-wrapper">
		<span class="scroll-top-inner">
			Top
		</span>
	</section>
</section>


<style>

#logo {
	margin-bottom: 20px;
	vertical-align: middle;
}

.banner container-fluid {
	height: 50px;
}

.nav_links {
/*	margin-top: 50px;*/
margin-top: -50px;
}

.navbar-header {
	margin-top: 10px;
}

</style>

app/views/artists/new.html.erb
<<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>

</header>


<div class="edit_title">
	<h1>Add Artist</h1>

</div>

<%= render 'form' %>

app/views/artists/show.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>



<body id="artist_body">



	<div class="artist_top">
		<h1 class="title"><%= @artist.stage_name %></h1>


		<div id="artist_img">
			<% if @artist.avatar.url == "/images/original/missing.png" %>
				<%= image_tag "blank_avatar.png", id:"profile", alt: "artist avatar", style: "width:20em;height:22em" %>
			<% else %>
				<%= image_tag @artist.avatar.url(:medium) , id: "profile", alt: "artist_avatar", style: "max-height:24em" %>
			<%end %>
		</div>
	</div>

	<div class="bio">
		<ul id="bio_list">
			<li class="bio_item"><em>Birth Name: </em> <%= @artist.birth_name %></li>
			<li class="bio_item"><em>Birthday: </em>  <%= @artist.display_birth_info %></li>
			<li class="bio_item"><em>Genres: </em>
			<% @artist.genres.each do |genre| %>
			  <%= link_to genre.name, genre_path(genre) %>
			<% end %></li>
			<li class="bio_item"><em>Description: </em> <%= @artist.description %></li>
		</ul>
	<p>	<%= link_to 'Edit Artist', edit_artist_path, :class => 'new_artist_link', :id=>'edit_artist' %></p>
	</div>


<%= render 'albums_list' %>

</body>