config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get 'login'
      post 'new_login'
      get 'logout'
    end
  end

  resources :artists do
    resource :artist_genres
    resources :albums do
      resources :songs
    end
  end

  resources :record_labels, path: 'record_labels'

  resources :genres

  root to: 'welcome#index'
  get 'search/search'


  get '/about', :to => 'welcome#about'

  get 'welcome/about'


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q]
      term = '%' + params[:q].strip.downcase + '%'
      @artists = Artist.where('lower(stage_name) like ?', term)
      @albums = Album.where('lower(title) like ?', term)
      @songs = Song.where('lower(title) like ?', term)
    end
  end
end

app/views/search/_album_result.html.erb
<div>
  <%= link_to album_result.title, artist_album_path(album_result.artist, album_result) %>
</div>

app/views/search/_artist_result.html.erb
<li><%= link_to artist_result.stage_name, artist_result, class: "artist" %></li>

app/views/search/_form.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-lg-4 col-lg-offset-4">
      <%= form_tag '/search/search', method: :get do %>
      <div class = "input-group">
        <%= text_field_tag :q, '', placeholder:'Search term here', class: "search" %>
          <span class="input-group-btn">
            <%= button_tag "Search", class: "btn btn-default", id: "search_but" %>
          </span>
      </div>
    </div>
  </div>
      <% end %>
</div>

app/views/search/_song_result.html.erb
<div>
  <%= link_to song_result.title, artist_album_song_path(song_result.artist, song_result.album, song_result) %>
</div>

app/views/search/search.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="banner container-fluid">
      <div class="navbar-header">
        <a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="header_ul nav navbar-nav navbar-right">
          <% if session[:user_id] %>
            <li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
            <li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
          <% else %>
            <li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
          <%end%>
          <li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
          <li class="main_ul"><a href='/artists'>Artists</a></li>
          <li class="main_ul"><a href='/genres'>Genres</a></li>
          <li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>


<div class = "container">

  <div class = "title">
    <h1>Search Results</h1>
  </div>

  <div class = "list">
    <ul>
    <h1>Artists</h1>
      <%= "No artists found" if (@artists.size < 1) %>
      <%= render partial: 'artist_result', collection: @artists %>
    <h1>Albums</h1>
      <%= render partial: 'album_result', collection: @albums %>
      <%= "No albums found" if (@albums.size < 1) %>
    <h1>Songs</h1>
      <%= "No songs found" if (@songs.size < 1) %>
      <%= render partial: 'song_result', collection: @songs %>
    </ul>
  </div>

  <%= render 'form' %>

</div>