config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get 'login'
      post 'new_login'
      get 'logout'
    end
  end

  resources :artists do
    resource :artist_genres
    resources :albums do
      resources :songs
    end
  end

  resources :record_labels, path: 'record_labels'

  resources :genres

  root to: 'welcome#index'
  get 'search/search'


  get '/about', :to => 'welcome#about'

  get 'welcome/about'


end

app/models/record_label.rb
class RecordLabel < ActiveRecord::Base
  has_many :artists

  validates :name, presence: true
  validates :name, uniqueness: {case_sensitive: false}

  def display_founding_date
    if founding_date != nil
      "Since #{founding_date}"
    end
  end
end

app/controllers/record_labels_controller.rb
class RecordLabelsController < ApplicationController

  def index
    @record_labels = RecordLabel.all
  end

  def show
    @record_label = RecordLabel.find(params[:id])
  end

  def new
    @record_label = RecordLabel.new
  end

  def create
    record_label = RecordLabel.find_or_create_by(record_label_params)
    if record_label.save
      redirect_to record_label_path(record_label)
    else
      @record_label = record_label
      render 'new'
    end
  end

  def edit
    @record_label = RecordLabel.find(params[:id])
  end

  def update
    record_label = RecordLabel.find(params[:id])
    if record_label.update_attributes(record_label_params)
      redirect_to record_label_path(record_label)
    else
      redirect_to edit_record_label_path(record_label)
    end
  end

  def destroy
    record_label = RecordLabel.find(params[:id])
    record_label.destroy
    redirect_to record_labels_path
  end

  def record_label_params
    params.require(:record_label).permit(
      :name,
      :founding_date)
  end
end

app/views/record_labels/_form.html.erb
<div class = "container">
  <%= form_for @record_label, html: {class: "form-horizontal"} do |f| %>
    <%= render 'shared/error_messages', target: @record_label %>
    <div class = "form-group">
      <%= f.label 'name', class: "col-sm-2 control-label"%>
      <div class = "col-sm-3">
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
    </div>
    <div class = "form-group">
      <%= f.label 'founding date' , class: "col-sm-2 control-label" %>
      <div class = "col-sm-1">
      <%= f.select :founding_date, (Time.zone.now.year - 60)..(Time.zone.now.year), class: "form-control" %>
      </div>
    </div>
    <div class = "form-group">
      <div class = "col-sm-offset-2 col-sm-1">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/record_labels/edit.html.erb
<div class = "edit_title">


<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>

<div id = "edit_title">
Edit <%= @record_label.name %>
</div>

<%= render 'form' %>
  <div class="container">
    <div class = "delete_entry">
      <%= link_to "Delete Record Label", record_label_path(@record_label), method: :delete %>
    </div>
  </div>

app/views/record_labels/index.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>


<div id="label-index-title">
	<div class="title">
	  <h1>Record Labels</h1>
	</div>
</div>

<div class="list">
  <ul>
    <% @record_labels.each do |label| %>
      <li><%= link_to label.name, record_label_path(label), class: "artist" %></li>
    <% end %>
  </ul>
</div>
>>>>>>> b4447da9c9ca1eea7f81d93b687dbf92c9b8cfb1

app/views/record_labels/new.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="banner container-fluid">
			<div class="navbar-header">
				<a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="header_ul nav navbar-nav navbar-right">
					<% if session[:user_id] %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
						<li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
					<% else %>
						<li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
					<%end%>
					<li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
					<li class="main_ul"><a href='/artists'>Artists</a></li>
					<li class="main_ul"><a href='/genres'>Genres</a></li>
					<li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>


<%= render 'form' %>

app/views/record_labels/show.html.erb
<body id = "artist_body">
  <header>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="banner container-fluid">
        <div class="navbar-header">
          <a class='navbar-brand'><%= link_to image_tag("irad_logo.png", :id=>'logo'), controller: 'welcome' %></a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="header_ul nav navbar-nav navbar-right">
            <% if session[:user_id] %>
              <li class='main_li top_header login'> <i class="fa fa-user login-icon-name"></i>  <%= link_to current_user.username, user_path(current_user), :class=> 'top_link'  %></li>
              <li class='main_li top_header'><%= link_to 'Logout', logout_users_path, :class=> 'top_link' %></a></li>
            <% else %>
              <li class='main_li top_header login'> <i class="fa fa-user login-icon"></i> <%= link_to 'Log In', login_users_path, :class=> 'top_link' %></li>
            <%end%>
            <li><%= link_to "About", welcome_about_path, class: "main_ul" %></li>
            <li class="main_ul"><a href='/artists'>Artists</a></li>
            <li class="main_ul"><a href='/genres'>Genres</a></li>
            <li class="main_ul"><a href='/record_labels'>Record Labels</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>


  <div class = "container">
    <div class = "title">
      <h1><%= @record_label.name %></h1>
    </div>
    <p class = "title_sub_heading">
      <% if @record_label.founding_date %>
        <%= @record_label.display_founding_date %>
      <% else %>
        <%= link_to "Add a founding date", edit_record_label_path %>
      <% end %>
    </p>

  <div class = "description">
    <h3>Artists on <%= @record_label.name %></h3>
    <% if @record_label.artists.size < 1 %>
      <%= link_to 'Add Artists', edit_record_label_path, class: "new_artist_link" %>
    <% else %>
      <ul>
      <% @record_label.artists.each do |artist| %>
        <div class = "label_artist">
          <li><%= link_to artist.stage_name, artist_path(artist) %></li>
        </div>
      <% end %>
      </ul>
    <% end %>

    <div class = "navigate_link">
      <%= link_to 'edit record label', edit_record_label_path %>
    </div>
    <div class = "navigate_link">
      <%= link_to 'back to all labels', record_labels_path %>
    </div>
  </div>

  </div>
</body>